# https://swiftbundler.dev/documentation/swift-bundler/configuration
format_version = 2

[apps.AmtrakStatus]
identifier = 'com.tonybark.AmtrakStatus'
product = 'AmtrakStatus'
version = '0.2.104'
icon = "./assets/icon.png"
category = "public.app-category.travel"


[[apps.AmtrakStatus.overlays]]
condition = "platform(macOS)"
icon = "./assets/icon.icns"

[[apps.AmtrakStatus.overlays]]
condition = "platform(macCatalyst)"
icon = "./assets/icon.icns"
