format_version = 2

[apps.AmtrakStatus]
identifier = 'com.tonybark.AmtrakStatus'
product = 'AmtrakStatus'
version = '0.2.101'
icon = "./assets/icon.png"


[[apps.AmtrakStatus.overlays]]
condition = "platform(macOS)"
icon = "./assets/icon.icns"

[[apps.AmtrakStatus.overlays]]
condition = "platform(macCatalyst)"
icon = "./assets/icon.icns"
